version: '3.1'
services:
    db:
        container_name: chat-postgres
        image: postgres:10-alpine
        ports:
            - '5434:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: chat
    admin:
        container_name: chat-adminer
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8082:8080